# SITE CONFIGURATION
title: Gerry Gan 
author: Gerry Gan
description: > # Meta description of Homepage
# baseurl:  # the subpath of your site, e.g. /blog
url: "https://jitli98.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Gerry Gan
  links:
    - https://github.com/jitli98
    - https://www.linkedin.com/in/jit-li-g-069970104/

# THEME SETTINGS
navigation: # Navigation links
  # - {name: 'Home', link: '/'}
  - {name: 'Projects', link: '/categories/#Projects'}
  - {name: 'About', link: '/about'}

tagline: >
    Hi! Welcome to my personal site. 

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: jitli98@uw.edu # email for form submission

github_username:  jitli9 # replace with your_github_username or comment to remove link from footer

# disqus:
#   shortname: jitgan # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
